//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Blocks {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Blocks() { }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Blocks", typeof(Blocks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        internal static string LabelBlockGroups => ResourceManager.GetString("LabelBlockGroups", resourceCulture);
        internal static string LabelBlockGroupName => ResourceManager.GetString("LabelBlockGroupName", resourceCulture);
        internal static string ButtonAddBlockGroup => ResourceManager.GetString("ButtonAddBlockGroup", resourceCulture);
        internal static string LabelBlocks => ResourceManager.GetString("LabelBlocks", resourceCulture);
        internal static string LabelBlockGroup => ResourceManager.GetString("LabelBlockGroup", resourceCulture);
        internal static string LabelBlockName => ResourceManager.GetString("LabelBlockName", resourceCulture);
        internal static string ButtonAddBlock => ResourceManager.GetString("ButtonAddBlock", resourceCulture);
        internal static string PlaceholderSearchBlocks => ResourceManager.GetString("PlaceholderSearchBlocks", resourceCulture);
        internal static string ButtonDeleteBlockGroup => ResourceManager.GetString("ButtonDeleteBlockGroup", resourceCulture);
        internal static string ButtonEditBlock => ResourceManager.GetString("ButtonEditBlock", resourceCulture);
        internal static string ButtonCopyBlock => ResourceManager.GetString("ButtonCopyBlock", resourceCulture);
        internal static string ButtonDeleteBlock => ResourceManager.GetString("ButtonDeleteBlock", resourceCulture);
    }
}
