//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CopyPrep {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CopyPrep() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.CopyPrep", typeof(CopyPrep).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelCopyPrep {
            get {
                return ResourceManager.GetString("LabelCopyPrep", resourceCulture);
            }
        }
        
        internal static string LabelQueued {
            get {
                return ResourceManager.GetString("LabelQueued", resourceCulture);
            }
        }
        
        internal static string LabelRunning {
            get {
                return ResourceManager.GetString("LabelRunning", resourceCulture);
            }
        }
        
        internal static string LabelFailed {
            get {
                return ResourceManager.GetString("LabelFailed", resourceCulture);
            }
        }
        
        internal static string LabelCompletedToday {
            get {
                return ResourceManager.GetString("LabelCompletedToday", resourceCulture);
            }
        }
        
        internal static string LabelAvgDuration {
            get {
                return ResourceManager.GetString("LabelAvgDuration", resourceCulture);
            }
        }
        
        internal static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        internal static string PlaceholderNameOrSourcePath {
            get {
                return ResourceManager.GetString("PlaceholderNameOrSourcePath", resourceCulture);
            }
        }
        
        internal static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        internal static string LabelLibrary {
            get {
                return ResourceManager.GetString("LabelLibrary", resourceCulture);
            }
        }
        
        internal static string TooltipRefresh {
            get {
                return ResourceManager.GetString("TooltipRefresh", resourceCulture);
            }
        }
        
        internal static string LabelAutoRefresh {
            get {
                return ResourceManager.GetString("LabelAutoRefresh", resourceCulture);
            }
        }
        
        internal static string LabelMedia {
            get {
                return ResourceManager.GetString("LabelMedia", resourceCulture);
            }
        }
        
        internal static string LabelProgress {
            get {
                return ResourceManager.GetString("LabelProgress", resourceCulture);
            }
        }
        
        internal static string LabelUpdated {
            get {
                return ResourceManager.GetString("LabelUpdated", resourceCulture);
            }
        }
        
        internal static string LabelAction {
            get {
                return ResourceManager.GetString("LabelAction", resourceCulture);
            }
        }
        
        internal static string LabelId {
            get {
                return ResourceManager.GetString("LabelId", resourceCulture);
            }
        }
        
        internal static string LabelPossiblyStalled {
            get {
                return ResourceManager.GetString("LabelPossiblyStalled", resourceCulture);
            }
        }
        
        internal static string LabelETA {
            get {
                return ResourceManager.GetString("LabelETA", resourceCulture);
            }
        }
        
        internal static string LabelSpeed {
            get {
                return ResourceManager.GetString("LabelSpeed", resourceCulture);
            }
        }
        
        internal static string LabelFrames {
            get {
                return ResourceManager.GetString("LabelFrames", resourceCulture);
            }
        }
        
        internal static string LabelOutput {
            get {
                return ResourceManager.GetString("LabelOutput", resourceCulture);
            }
        }
        
        internal static string TooltipRetry {
            get {
                return ResourceManager.GetString("TooltipRetry", resourceCulture);
            }
        }
        
        internal static string TooltipCancel {
            get {
                return ResourceManager.GetString("TooltipCancel", resourceCulture);
            }
        }
        
        internal static string LabelNoMatchingItems {
            get {
                return ResourceManager.GetString("LabelNoMatchingItems", resourceCulture);
            }
        }
        
        internal static string LabelLoading {
            get {
                return ResourceManager.GetString("LabelLoading", resourceCulture);
            }
        }
        
        internal static string LabelDetails {
            get {
                return ResourceManager.GetString("LabelDetails", resourceCulture);
            }
        }
        
        internal static string LabelSelectItem {
            get {
                return ResourceManager.GetString("LabelSelectItem", resourceCulture);
            }
        }
        
        internal static string LabelCurrentActivity {
            get {
                return ResourceManager.GetString("LabelCurrentActivity", resourceCulture);
            }
        }
        
        internal static string LabelProcessed {
            get {
                return ResourceManager.GetString("LabelProcessed", resourceCulture);
            }
        }
        
        internal static string LabelLastProgress {
            get {
                return ResourceManager.GetString("LabelLastProgress", resourceCulture);
            }
        }
        
        internal static string LabelRealtimeMetrics {
            get {
                return ResourceManager.GetString("LabelRealtimeMetrics", resourceCulture);
            }
        }
        
        internal static string LabelReason {
            get {
                return ResourceManager.GetString("LabelReason", resourceCulture);
            }
        }
        
        internal static string LabelLastError {
            get {
                return ResourceManager.GetString("LabelLastError", resourceCulture);
            }
        }
        
        internal static string LabelRecentEvents {
            get {
                return ResourceManager.GetString("LabelRecentEvents", resourceCulture);
            }
        }
        
        internal static string LabelNoLogEntries {
            get {
                return ResourceManager.GetString("LabelNoLogEntries", resourceCulture);
            }
        }
        
        internal static string StatusQueued {
            get {
                return ResourceManager.GetString("StatusQueued", resourceCulture);
            }
        }
        
        internal static string StatusStarting {
            get {
                return ResourceManager.GetString("StatusStarting", resourceCulture);
            }
        }
        
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        internal static string StatusDone {
            get {
                return ResourceManager.GetString("StatusDone", resourceCulture);
            }
        }
        
        internal static string StatusFailed {
            get {
                return ResourceManager.GetString("StatusFailed", resourceCulture);
            }
        }
        
        internal static string LabelDash {
            get {
                return ResourceManager.GetString("LabelDash", resourceCulture);
            }
        }
    }
}
