//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Decos {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Decos() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Decos", typeof(Decos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelDecoGroups {
            get {
                return ResourceManager.GetString("LabelDecoGroups", resourceCulture);
            }
        }
        
        internal static string LabelDecoGroupName {
            get {
                return ResourceManager.GetString("LabelDecoGroupName", resourceCulture);
            }
        }
        
        internal static string ButtonAddDecoGroup {
            get {
                return ResourceManager.GetString("ButtonAddDecoGroup", resourceCulture);
            }
        }
        
        internal static string LabelDecos {
            get {
                return ResourceManager.GetString("LabelDecos", resourceCulture);
            }
        }
        
        internal static string LabelDecoGroup {
            get {
                return ResourceManager.GetString("LabelDecoGroup", resourceCulture);
            }
        }
        
        internal static string LabelDecoName {
            get {
                return ResourceManager.GetString("LabelDecoName", resourceCulture);
            }
        }
        
        internal static string ButtonAddDeco {
            get {
                return ResourceManager.GetString("ButtonAddDeco", resourceCulture);
            }
        }
    }
}
