//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FFmpeg {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FFmpeg() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.FFmpeg", typeof(FFmpeg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddProfile {
            get {
                return ResourceManager.GetString("ButtonAddProfile", resourceCulture);
            }
        }
        
        internal static string LabelFFmpegProfiles {
            get {
                return ResourceManager.GetString("LabelFFmpegProfiles", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelResolution {
            get {
                return ResourceManager.GetString("LabelResolution", resourceCulture);
            }
        }
        
        internal static string LabelVideoFormat {
            get {
                return ResourceManager.GetString("LabelVideoFormat", resourceCulture);
            }
        }
        
        internal static string LabelAudioFormat {
            get {
                return ResourceManager.GetString("LabelAudioFormat", resourceCulture);
            }
        }
        
        internal static string ButtonEditProfile {
            get {
                return ResourceManager.GetString("ButtonEditProfile", resourceCulture);
            }
        }
        
        internal static string ButtonCopyProfile {
            get {
                return ResourceManager.GetString("ButtonCopyProfile", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteProfile {
            get {
                return ResourceManager.GetString("ButtonDeleteProfile", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteProfileConfirm {
            get {
                return ResourceManager.GetString("ButtonDeleteProfileConfirm", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteProfileSuccess {
            get {
                return ResourceManager.GetString("ButtonDeleteProfileSuccess", resourceCulture);
            }
        }
        
        internal static string ButtonCopyProfileSuccess {
            get {
                return ResourceManager.GetString("ButtonCopyProfileSuccess", resourceCulture);
            }
        }
        
        internal static string DialogDeleteFFmpegProfile {
            get {
                return ResourceManager.GetString("DialogDeleteFFmpegProfile", resourceCulture);
            }
        }
        
        internal static string DialogCopyFFmpegProfile {
            get {
                return ResourceManager.GetString("DialogCopyFFmpegProfile", resourceCulture);
            }
        }
    }
}
