//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FillerPresets {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FillerPresets() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.FillerPresets", typeof(FillerPresets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddFillerPreset {
            get {
                return ResourceManager.GetString("ButtonAddFillerPreset", resourceCulture);
            }
        }
        
        internal static string LabelFillerPresets {
            get {
                return ResourceManager.GetString("LabelFillerPresets", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelFillerKind {
            get {
                return ResourceManager.GetString("LabelFillerKind", resourceCulture);
            }
        }
        
        internal static string LabelPreRoll {
            get {
                return ResourceManager.GetString("LabelPreRoll", resourceCulture);
            }
        }
        
        internal static string LabelMidRoll {
            get {
                return ResourceManager.GetString("LabelMidRoll", resourceCulture);
            }
        }
        
        internal static string LabelPostRoll {
            get {
                return ResourceManager.GetString("LabelPostRoll", resourceCulture);
            }
        }
        
        internal static string LabelFallback {
            get {
                return ResourceManager.GetString("LabelFallback", resourceCulture);
            }
        }
        
        internal static string LabelTail {
            get {
                return ResourceManager.GetString("LabelTail", resourceCulture);
            }
        }
        
        internal static string LabelNone {
            get {
                return ResourceManager.GetString("LabelNone", resourceCulture);
            }
        }
        
        internal static string TooltipEditFillerPreset {
            get {
                return ResourceManager.GetString("TooltipEditFillerPreset", resourceCulture);
            }
        }
        
        internal static string TooltipDeleteFillerPreset {
            get {
                return ResourceManager.GetString("TooltipDeleteFillerPreset", resourceCulture);
            }
        }
        
        internal static string DialogDeleteFillerPreset {
            get {
                return ResourceManager.GetString("DialogDeleteFillerPreset", resourceCulture);
            }
        }
    }
}
