//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelDatabaseInitializing {
            get {
                return ResourceManager.GetString("LabelDatabaseInitializing", resourceCulture);
            }
        }
        
        internal static string LabelPleaseWait {
            get {
                return ResourceManager.GetString("LabelPleaseWait", resourceCulture);
            }
        }
        
        internal static string LabelDatabaseWillRefresh {
            get {
                return ResourceManager.GetString("LabelDatabaseWillRefresh", resourceCulture);
            }
        }
        
        internal static string LabelSearchIndexInitializing {
            get {
                return ResourceManager.GetString("LabelSearchIndexInitializing", resourceCulture);
            }
        }
        
        internal static string LabelSearchIndexWillRefresh {
            get {
                return ResourceManager.GetString("LabelSearchIndexWillRefresh", resourceCulture);
            }
        }
        
        internal static string LabelHealthChecks {
            get {
                return ResourceManager.GetString("LabelHealthChecks", resourceCulture);
            }
        }
        
        internal static string LabelCheck {
            get {
                return ResourceManager.GetString("LabelCheck", resourceCulture);
            }
        }
        
        internal static string LabelMessage {
            get {
                return ResourceManager.GetString("LabelMessage", resourceCulture);
            }
        }
        
        internal static string LabelFullChangelogOnGitHub {
            get {
                return ResourceManager.GetString("LabelFullChangelogOnGitHub", resourceCulture);
            }
        }
    }
}
