//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Libraries {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Libraries() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Libraries", typeof(Libraries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelLibraries {
            get {
                return ResourceManager.GetString("LabelLibraries", resourceCulture);
            }
        }
        
        internal static string LabelLibraryKind {
            get {
                return ResourceManager.GetString("LabelLibraryKind", resourceCulture);
            }
        }
        
        internal static string LabelServerName {
            get {
                return ResourceManager.GetString("LabelServerName", resourceCulture);
            }
        }
        
        internal static string LabelLibraryName {
            get {
                return ResourceManager.GetString("LabelLibraryName", resourceCulture);
            }
        }
        
        internal static string LabelMediaKind {
            get {
                return ResourceManager.GetString("LabelMediaKind", resourceCulture);
            }
        }
        
        internal static string LabelMusicVideos {
            get {
                return ResourceManager.GetString("LabelMusicVideos", resourceCulture);
            }
        }
        
        internal static string LabelOtherVideos {
            get {
                return ResourceManager.GetString("LabelOtherVideos", resourceCulture);
            }
        }
        
        internal static string LabelRemoteStreams {
            get {
                return ResourceManager.GetString("LabelRemoteStreams", resourceCulture);
            }
        }
        
        internal static string LabelExternalCollections {
            get {
                return ResourceManager.GetString("LabelExternalCollections", resourceCulture);
            }
        }
        
        internal static string ButtonDeepScanLibrary {
            get {
                return ResourceManager.GetString("ButtonDeepScanLibrary", resourceCulture);
            }
        }
        
        internal static string ButtonScanLibrary {
            get {
                return ResourceManager.GetString("ButtonScanLibrary", resourceCulture);
            }
        }
        
        internal static string ButtonSearchLibrary {
            get {
                return ResourceManager.GetString("ButtonSearchLibrary", resourceCulture);
            }
        }
        
        internal static string ButtonDeepScanCollections {
            get {
                return ResourceManager.GetString("ButtonDeepScanCollections", resourceCulture);
            }
        }
        
        internal static string ButtonScanCollections {
            get {
                return ResourceManager.GetString("ButtonScanCollections", resourceCulture);
            }
        }
    }
}
