//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalLibraries {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalLibraries() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.LocalLibraries", typeof(LocalLibraries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddLocalLibrary {
            get {
                return ResourceManager.GetString("ButtonAddLocalLibrary", resourceCulture);
            }
        }
        
        internal static string LabelLocalLibraries {
            get {
                return ResourceManager.GetString("LabelLocalLibraries", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelMediaKind {
            get {
                return ResourceManager.GetString("LabelMediaKind", resourceCulture);
            }
        }
        
        internal static string TooltipEditLibrary {
            get {
                return ResourceManager.GetString("TooltipEditLibrary", resourceCulture);
            }
        }
        
        internal static string TooltipDeleteLibrary {
            get {
                return ResourceManager.GetString("TooltipDeleteLibrary", resourceCulture);
            }
        }
        
        internal static string LabelMovies {
            get {
                return ResourceManager.GetString("LabelMovies", resourceCulture);
            }
        }
        
        internal static string LabelShows {
            get {
                return ResourceManager.GetString("LabelShows", resourceCulture);
            }
        }
        
        internal static string LabelMusicVideos {
            get {
                return ResourceManager.GetString("LabelMusicVideos", resourceCulture);
            }
        }
        
        internal static string LabelOtherVideos {
            get {
                return ResourceManager.GetString("LabelOtherVideos", resourceCulture);
            }
        }
        
        internal static string LabelSongs {
            get {
                return ResourceManager.GetString("LabelSongs", resourceCulture);
            }
        }
        
        internal static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        internal static string LabelRemoteStreams {
            get {
                return ResourceManager.GetString("LabelRemoteStreams", resourceCulture);
            }
        }
        
        internal static string LabelUnknown {
            get {
                return ResourceManager.GetString("LabelUnknown", resourceCulture);
            }
        }
        
        internal static string DialogDeleteLibrary {
            get {
                return ResourceManager.GetString("DialogDeleteLibrary", resourceCulture);
            }
        }
        
        internal static string LabelContainsMediaItems {
            get {
                return ResourceManager.GetString("LabelContainsMediaItems", resourceCulture);
            }
        }
    }
}
