//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManualCollections {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManualCollections() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.ManualCollections", typeof(ManualCollections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelManualCollections {
            get {
                return ResourceManager.GetString("LabelManualCollections", resourceCulture);
            }
        }
        
        internal static string ButtonAddCollection {
            get {
                return ResourceManager.GetString("ButtonAddCollection", resourceCulture);
            }
        }
        
        internal static string LabelSearchManualCollections {
            get {
                return ResourceManager.GetString("LabelSearchManualCollections", resourceCulture);
            }
        }
        
        internal static string TooltipEditCollection {
            get {
                return ResourceManager.GetString("TooltipEditCollection", resourceCulture);
            }
        }
        
        internal static string TooltipDeleteCollection {
            get {
                return ResourceManager.GetString("TooltipDeleteCollection", resourceCulture);
            }
        }
        
        internal static string LabelDeleteCollection {
            get {
                return ResourceManager.GetString("LabelDeleteCollection", resourceCulture);
            }
        }
    }
}
