//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovieList {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovieList() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.MovieList", typeof(MovieList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelMovies {
            get {
                return ResourceManager.GetString("LabelMovies", resourceCulture);
            }
        }
        
        internal static string ButtonAddToCollection {
            get {
                return ResourceManager.GetString("ButtonAddToCollection", resourceCulture);
            }
        }
        
        internal static string ErrorAddingMovieToCollection {
            get {
                return ResourceManager.GetString("ErrorAddingMovieToCollection", resourceCulture);
            }
        }
        
        internal static string AddedMovieToCollection {
            get {
                return ResourceManager.GetString("AddedMovieToCollection", resourceCulture);
            }
        }
        
        internal static string LabelItem {
            get {
                return ResourceManager.GetString("LabelItem", resourceCulture);
            }
        }
        
        internal static string LabelItems {
            get {
                return ResourceManager.GetString("LabelItems", resourceCulture);
            }
        }
        
        internal static string LabelSelected {
            get {
                return ResourceManager.GetString("LabelSelected", resourceCulture);
            }
        }
    }
}
