//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Playouts {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Playouts() { }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Playouts", typeof(Playouts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        internal static string ButtonAddPlayout => ResourceManager.GetString("ButtonAddPlayout", resourceCulture);
        internal static string ButtonAddClassic => ResourceManager.GetString("ButtonAddClassic", resourceCulture);
        internal static string ButtonAddBlock => ResourceManager.GetString("ButtonAddBlock", resourceCulture);
        internal static string ButtonAddSequential => ResourceManager.GetString("ButtonAddSequential", resourceCulture);
        internal static string ButtonAddScripted => ResourceManager.GetString("ButtonAddScripted", resourceCulture);
        internal static string ButtonAddJson => ResourceManager.GetString("ButtonAddJson", resourceCulture);
        internal static string ButtonResetAllPlayouts => ResourceManager.GetString("ButtonResetAllPlayouts", resourceCulture);
        internal static string LabelPlayouts => ResourceManager.GetString("LabelPlayouts", resourceCulture);
        internal static string PlaceholderSearchPlayouts => ResourceManager.GetString("PlaceholderSearchPlayouts", resourceCulture);
        internal static string LabelChannel => ResourceManager.GetString("LabelChannel", resourceCulture);
        internal static string LabelDefaultSchedule => ResourceManager.GetString("LabelDefaultSchedule", resourceCulture);
        internal static string LabelScheduleKind => ResourceManager.GetString("LabelScheduleKind", resourceCulture);
        internal static string LabelBlock => ResourceManager.GetString("LabelBlock", resourceCulture);
        internal static string LabelSequential => ResourceManager.GetString("LabelSequential", resourceCulture);
        internal static string LabelScripted => ResourceManager.GetString("LabelScripted", resourceCulture);
        internal static string LabelJsonDizqueTV => ResourceManager.GetString("LabelJsonDizqueTV", resourceCulture);
        internal static string ButtonEditPlayout => ResourceManager.GetString("ButtonEditPlayout", resourceCulture);
        internal static string ButtonRefreshPlayout => ResourceManager.GetString("ButtonRefreshPlayout", resourceCulture);
        internal static string ButtonScheduleReset => ResourceManager.GetString("ButtonScheduleReset", resourceCulture);
        internal static string ButtonDeletePlayout => ResourceManager.GetString("ButtonDeletePlayout", resourceCulture);
        internal static string ButtonCopyPlayout => ResourceManager.GetString("ButtonCopyPlayout", resourceCulture);
        internal static string DialogDeletePlayout => ResourceManager.GetString("DialogDeletePlayout", resourceCulture);
        internal static string ButtonAddClassicPlayout => ResourceManager.GetString("ButtonAddClassicPlayout", resourceCulture);
        internal static string ButtonAddBlockPlayout => ResourceManager.GetString("ButtonAddBlockPlayout", resourceCulture);
        internal static string ButtonAddSequentialPlayout => ResourceManager.GetString("ButtonAddSequentialPlayout", resourceCulture);
        internal static string ButtonAddScriptedPlayout => ResourceManager.GetString("ButtonAddScriptedPlayout", resourceCulture);
        internal static string ButtonAddJsonPlayout => ResourceManager.GetString("ButtonAddJsonPlayout", resourceCulture);
    }
}
