//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlexMediaSources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlexMediaSources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.PlexMediaSources", typeof(PlexMediaSources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonDisconnect {
            get {
                return ResourceManager.GetString("ButtonDisconnect", resourceCulture);
            }
        }
        
        internal static string ButtonConnect {
            get {
                return ResourceManager.GetString("ButtonConnect", resourceCulture);
            }
        }
        
        internal static string ButtonEditConnection {
            get {
                return ResourceManager.GetString("ButtonEditConnection", resourceCulture);
            }
        }
        
        internal static string ButtonFixConnection {
            get {
                return ResourceManager.GetString("ButtonFixConnection", resourceCulture);
            }
        }
        
        internal static string LabelMediaSources {
            get {
                return ResourceManager.GetString("LabelMediaSources", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        internal static string TooltipRefreshLibraries {
            get {
                return ResourceManager.GetString("TooltipRefreshLibraries", resourceCulture);
            }
        }
        
        internal static string TooltipEditLibraries {
            get {
                return ResourceManager.GetString("TooltipEditLibraries", resourceCulture);
            }
        }
        
        internal static string TooltipEditPathReplacements {
            get {
                return ResourceManager.GetString("TooltipEditPathReplacements", resourceCulture);
            }
        }
        
        internal static string DialogDisconnect {
            get {
                return ResourceManager.GetString("DialogDisconnect", resourceCulture);
            }
        }
        
        internal static string LabelPlexMediaSources {
            get {
                return ResourceManager.GetString("LabelPlexMediaSources", resourceCulture);
            }
        }
        
        internal static string ButtonSignOut {
            get {
                return ResourceManager.GetString("ButtonSignOut", resourceCulture);
            }
        }
        
        internal static string ButtonSignIn {
            get {
                return ResourceManager.GetString("ButtonSignIn", resourceCulture);
            }
        }
        
        internal static string ButtonFixCredentials {
            get {
                return ResourceManager.GetString("ButtonFixCredentials", resourceCulture);
            }
        }
        
        internal static string DialogSignOut {
            get {
                return ResourceManager.GetString("DialogSignOut", resourceCulture);
            }
        }
    }
}
