//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RemoteStreamList {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemoteStreamList() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.RemoteStreamList", typeof(RemoteStreamList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelRemoteStreams {
            get {
                return ResourceManager.GetString("LabelRemoteStreams", resourceCulture);
            }
        }
        
        internal static string DialogAddToCollection {
            get {
                return ResourceManager.GetString("DialogAddToCollection", resourceCulture);
            }
        }
        
        internal static string EntityTypeRemoteStream {
            get {
                return ResourceManager.GetString("EntityTypeRemoteStream", resourceCulture);
            }
        }
        
        internal static string MessageAddedRemoteStreamToCollection {
            get {
                return ResourceManager.GetString("MessageAddedRemoteStreamToCollection", resourceCulture);
            }
        }
        
        internal static string MessageUnexpectedErrorAddingRemoteStreamToCollection {
            get {
                return ResourceManager.GetString("MessageUnexpectedErrorAddingRemoteStreamToCollection", resourceCulture);
            }
        }
    }
}
