//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Schedules {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Schedules() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Schedules", typeof(Schedules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddSchedule {
            get {
                return ResourceManager.GetString("ButtonAddSchedule", resourceCulture);
            }
        }
        
        internal static string LabelSchedules {
            get {
                return ResourceManager.GetString("LabelSchedules", resourceCulture);
            }
        }
        
        internal static string PlaceholderSearchSchedules {
            get {
                return ResourceManager.GetString("PlaceholderSearchSchedules", resourceCulture);
            }
        }
        
        internal static string ButtonEditProperties {
            get {
                return ResourceManager.GetString("ButtonEditProperties", resourceCulture);
            }
        }
        
        internal static string ButtonEditScheduleItems {
            get {
                return ResourceManager.GetString("ButtonEditScheduleItems", resourceCulture);
            }
        }
        
        internal static string ButtonCopySchedule {
            get {
                return ResourceManager.GetString("ButtonCopySchedule", resourceCulture);
            }
        }
        
        internal static string ButtonTroubleshoot {
            get {
                return ResourceManager.GetString("ButtonTroubleshoot", resourceCulture);
            }
        }
        
        internal static string ButtonDeleteSchedule {
            get {
                return ResourceManager.GetString("ButtonDeleteSchedule", resourceCulture);
            }
        }
        
        internal static string LabelStartTime {
            get {
                return ResourceManager.GetString("LabelStartTime", resourceCulture);
            }
        }
        
        internal static string LabelCollection {
            get {
                return ResourceManager.GetString("LabelCollection", resourceCulture);
            }
        }
        
        internal static string LabelPlayoutMode {
            get {
                return ResourceManager.GetString("LabelPlayoutMode", resourceCulture);
            }
        }
        
        internal static string LabelDynamic {
            get {
                return ResourceManager.GetString("LabelDynamic", resourceCulture);
            }
        }
        
        internal static string LabelItems {
            get {
                return ResourceManager.GetString("LabelItems", resourceCulture);
            }
        }
        
        internal static string DialogDeleteSchedule {
            get {
                return ResourceManager.GetString("DialogDeleteSchedule", resourceCulture);
            }
        }
        
        internal static string DialogCopySchedule {
            get {
                return ResourceManager.GetString("DialogCopySchedule", resourceCulture);
            }
        }
    }
}
