//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Search {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Search() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Search", typeof(Search).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddToCollection {
            get {
                return ResourceManager.GetString("ButtonAddToCollection", resourceCulture);
            }
        }
        
        internal static string ButtonAddToPlaylist {
            get {
                return ResourceManager.GetString("ButtonAddToPlaylist", resourceCulture);
            }
        }
        
        internal static string ButtonAddSelectedToCopyPrep {
            get {
                return ResourceManager.GetString("ButtonAddSelectedToCopyPrep", resourceCulture);
            }
        }
        
        internal static string ButtonClearSelection {
            get {
                return ResourceManager.GetString("ButtonClearSelection", resourceCulture);
            }
        }
        
        internal static string ButtonAddAll {
            get {
                return ResourceManager.GetString("ButtonAddAll", resourceCulture);
            }
        }
        
        internal static string ButtonSelectAllEligible {
            get {
                return ResourceManager.GetString("ButtonSelectAllEligible", resourceCulture);
            }
        }
        
        internal static string ButtonSaveAs {
            get {
                return ResourceManager.GetString("ButtonSaveAs", resourceCulture);
            }
        }
        
        internal static string ButtonSaveAsSmartCollection {
            get {
                return ResourceManager.GetString("ButtonSaveAsSmartCollection", resourceCulture);
            }
        }
        
        internal static string ButtonAddAllToCollection {
            get {
                return ResourceManager.GetString("ButtonAddAllToCollection", resourceCulture);
            }
        }
        
        internal static string ButtonAddAllToPlaylist {
            get {
                return ResourceManager.GetString("ButtonAddAllToPlaylist", resourceCulture);
            }
        }
        
        internal static string LabelMovies {
            get {
                return ResourceManager.GetString("LabelMovies", resourceCulture);
            }
        }
        
        internal static string LabelShows {
            get {
                return ResourceManager.GetString("LabelShows", resourceCulture);
            }
        }
        
        internal static string LabelSeasons {
            get {
                return ResourceManager.GetString("LabelSeasons", resourceCulture);
            }
        }
        
        internal static string LabelEpisodes {
            get {
                return ResourceManager.GetString("LabelEpisodes", resourceCulture);
            }
        }
        
        internal static string LabelArtists {
            get {
                return ResourceManager.GetString("LabelArtists", resourceCulture);
            }
        }
        
        internal static string LabelMusicVideos {
            get {
                return ResourceManager.GetString("LabelMusicVideos", resourceCulture);
            }
        }
        
        internal static string LabelOtherVideos {
            get {
                return ResourceManager.GetString("LabelOtherVideos", resourceCulture);
            }
        }
        
        internal static string LabelSongs {
            get {
                return ResourceManager.GetString("LabelSongs", resourceCulture);
            }
        }
        
        internal static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        internal static string LabelRemoteStreams {
            get {
                return ResourceManager.GetString("LabelRemoteStreams", resourceCulture);
            }
        }
        
        internal static string LinkSeeAll {
            get {
                return ResourceManager.GetString("LinkSeeAll", resourceCulture);
            }
        }
        
        internal static string DialogAddToCollection {
            get {
                return ResourceManager.GetString("DialogAddToCollection", resourceCulture);
            }
        }
        
        internal static string MessageNeedsCopyPrep {
            get {
                return ResourceManager.GetString("MessageNeedsCopyPrep", resourceCulture);
            }
        }
        
        internal static string MessageCopyReady {
            get {
                return ResourceManager.GetString("MessageCopyReady", resourceCulture);
            }
        }
        
        internal static string MessageNoEligibleItems {
            get {
                return ResourceManager.GetString("MessageNoEligibleItems", resourceCulture);
            }
        }
        
        internal static string MessageQueuedResult {
            get {
                return ResourceManager.GetString("MessageQueuedResult", resourceCulture);
            }
        }
        
        internal static string MessageAddedToCollection {
            get {
                return ResourceManager.GetString("MessageAddedToCollection", resourceCulture);
            }
        }
        
        internal static string MessageAddedSeasonToCollection {
            get {
                return ResourceManager.GetString("MessageAddedSeasonToCollection", resourceCulture);
            }
        }
        
        internal static string MessageUnexpectedError {
            get {
                return ResourceManager.GetString("MessageUnexpectedError", resourceCulture);
            }
        }
        
        internal static string LabelSearchResults {
            get {
                return ResourceManager.GetString("LabelSearchResults", resourceCulture);
            }
        }
    }
}
