//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmartCollections {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmartCollections() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.SmartCollections", typeof(SmartCollections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelSmartCollections {
            get {
                return ResourceManager.GetString("LabelSmartCollections", resourceCulture);
            }
        }
        
        internal static string LabelSearchSmartCollections {
            get {
                return ResourceManager.GetString("LabelSearchSmartCollections", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string TooltipEditSmartCollection {
            get {
                return ResourceManager.GetString("TooltipEditSmartCollection", resourceCulture);
            }
        }
        
        internal static string TooltipSearchSmartCollection {
            get {
                return ResourceManager.GetString("TooltipSearchSmartCollection", resourceCulture);
            }
        }
        
        internal static string TooltipDeleteSmartCollection {
            get {
                return ResourceManager.GetString("TooltipDeleteSmartCollection", resourceCulture);
            }
        }
    }
}
