//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelevisionSeasonList {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelevisionSeasonList() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.TelevisionSeasonList", typeof(TelevisionSeasonList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelSeasons {
            get {
                return ResourceManager.GetString("LabelSeasons", resourceCulture);
            }
        }
        
        internal static string LabelActors {
            get {
                return ResourceManager.GetString("LabelActors", resourceCulture);
            }
        }
        
        internal static string LabelContentRatings {
            get {
                return ResourceManager.GetString("LabelContentRatings", resourceCulture);
            }
        }
        
        internal static string LabelLanguages {
            get {
                return ResourceManager.GetString("LabelLanguages", resourceCulture);
            }
        }
        
        internal static string LabelStudios {
            get {
                return ResourceManager.GetString("LabelStudios", resourceCulture);
            }
        }
        
        internal static string LabelNetworks {
            get {
                return ResourceManager.GetString("LabelNetworks", resourceCulture);
            }
        }
        
        internal static string LabelGenres {
            get {
                return ResourceManager.GetString("LabelGenres", resourceCulture);
            }
        }
        
        internal static string LabelTags {
            get {
                return ResourceManager.GetString("LabelTags", resourceCulture);
            }
        }
        
        internal static string LabelAddTo {
            get {
                return ResourceManager.GetString("LabelAddTo", resourceCulture);
            }
        }
        
        internal static string ButtonScan {
            get {
                return ResourceManager.GetString("ButtonScan", resourceCulture);
            }
        }
        
        internal static string ButtonQuickScan {
            get {
                return ResourceManager.GetString("ButtonQuickScan", resourceCulture);
            }
        }
        
        internal static string ButtonDeepScan {
            get {
                return ResourceManager.GetString("ButtonDeepScan", resourceCulture);
            }
        }
        
        internal static string ButtonCollection {
            get {
                return ResourceManager.GetString("ButtonCollection", resourceCulture);
            }
        }
        
        internal static string ButtonPlaylist {
            get {
                return ResourceManager.GetString("ButtonPlaylist", resourceCulture);
            }
        }
        
        internal static string ButtonSchedule {
            get {
                return ResourceManager.GetString("ButtonSchedule", resourceCulture);
            }
        }
        
        internal static string ButtonAddToCollection {
            get {
                return ResourceManager.GetString("ButtonAddToCollection", resourceCulture);
            }
        }
        
        internal static string ButtonAddToPlaylist {
            get {
                return ResourceManager.GetString("ButtonAddToPlaylist", resourceCulture);
            }
        }
        
        internal static string ButtonAddToSchedule {
            get {
                return ResourceManager.GetString("ButtonAddToSchedule", resourceCulture);
            }
        }
        
        internal static string ErrorAddingSeasonToCollection {
            get {
                return ResourceManager.GetString("ErrorAddingSeasonToCollection", resourceCulture);
            }
        }
        
        internal static string MessageAddedSeasonToCollection {
            get {
                return ResourceManager.GetString("MessageAddedSeasonToCollection", resourceCulture);
            }
        }
        
        internal static string ErrorScanningShow {
            get {
                return ResourceManager.GetString("ErrorScanningShow", resourceCulture);
            }
        }
        
        internal static string MessageScanningShowComplete {
            get {
                return ResourceManager.GetString("MessageScanningShowComplete", resourceCulture);
            }
        }
    }
}
