//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TelevisionEpisodeList {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelevisionEpisodeList() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.TelevisionEpisodeList", typeof(TelevisionEpisodeList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelEpisodes {
            get {
                return ResourceManager.GetString("LabelEpisodes", resourceCulture);
            }
        }
        
        internal static string ButtonAddToCollection {
            get {
                return ResourceManager.GetString("ButtonAddToCollection", resourceCulture);
            }
        }
        
        internal static string ButtonAddToPlaylist {
            get {
                return ResourceManager.GetString("ButtonAddToPlaylist", resourceCulture);
            }
        }
        
        internal static string ButtonAddToSchedule {
            get {
                return ResourceManager.GetString("ButtonAddToSchedule", resourceCulture);
            }
        }
        
        internal static string LabelAddTo {
            get {
                return ResourceManager.GetString("LabelAddTo", resourceCulture);
            }
        }
        
        internal static string ButtonShowMediaInfo {
            get {
                return ResourceManager.GetString("ButtonShowMediaInfo", resourceCulture);
            }
        }
        
        internal static string ButtonTroubleshootPlayback {
            get {
                return ResourceManager.GetString("ButtonTroubleshootPlayback", resourceCulture);
            }
        }
        
        internal static string LabelFileNotFound {
            get {
                return ResourceManager.GetString("LabelFileNotFound", resourceCulture);
            }
        }
        
        internal static string LabelUnavailable {
            get {
                return ResourceManager.GetString("LabelUnavailable", resourceCulture);
            }
        }
        
        internal static string LabelReleased {
            get {
                return ResourceManager.GetString("LabelReleased", resourceCulture);
            }
        }
        
        internal static string LabelDirectors {
            get {
                return ResourceManager.GetString("LabelDirectors", resourceCulture);
            }
        }
        
        internal static string LabelWriters {
            get {
                return ResourceManager.GetString("LabelWriters", resourceCulture);
            }
        }
        
        internal static string ErrorAddingEpisodeToCollection {
            get {
                return ResourceManager.GetString("ErrorAddingEpisodeToCollection", resourceCulture);
            }
        }
        
        internal static string ErrorAddingEpisodeToPlaylist {
            get {
                return ResourceManager.GetString("ErrorAddingEpisodeToPlaylist", resourceCulture);
            }
        }
        
        internal static string ErrorLoadingMediaInfo {
            get {
                return ResourceManager.GetString("ErrorLoadingMediaInfo", resourceCulture);
            }
        }
        
        internal static string MessageAddedToCollection {
            get {
                return ResourceManager.GetString("MessageAddedToCollection", resourceCulture);
            }
        }
        
        internal static string MessageAddedToPlaylist {
            get {
                return ResourceManager.GetString("MessageAddedToPlaylist", resourceCulture);
            }
        }
    }
}
