//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LabelTemplateGroups {
            get {
                return ResourceManager.GetString("LabelTemplateGroups", resourceCulture);
            }
        }
        
        internal static string LabelTemplateGroupName {
            get {
                return ResourceManager.GetString("LabelTemplateGroupName", resourceCulture);
            }
        }
        
        internal static string ButtonAddTemplateGroup {
            get {
                return ResourceManager.GetString("ButtonAddTemplateGroup", resourceCulture);
            }
        }
        
        internal static string LabelTemplates {
            get {
                return ResourceManager.GetString("LabelTemplates", resourceCulture);
            }
        }
        
        internal static string LabelTemplateGroup {
            get {
                return ResourceManager.GetString("LabelTemplateGroup", resourceCulture);
            }
        }
        
        internal static string LabelTemplateName {
            get {
                return ResourceManager.GetString("LabelTemplateName", resourceCulture);
            }
        }
        
        internal static string ButtonAddTemplate {
            get {
                return ResourceManager.GetString("ButtonAddTemplate", resourceCulture);
            }
        }
    }
}
