//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraktLists {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraktLists() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.TraktLists", typeof(TraktLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddTraktList {
            get {
                return ResourceManager.GetString("ButtonAddTraktList", resourceCulture);
            }
        }
        
        internal static string LabelTraktLists {
            get {
                return ResourceManager.GetString("LabelTraktLists", resourceCulture);
            }
        }
        
        internal static string LabelId {
            get {
                return ResourceManager.GetString("LabelId", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelLastUpdated {
            get {
                return ResourceManager.GetString("LabelLastUpdated", resourceCulture);
            }
        }
        
        internal static string LabelItemCount {
            get {
                return ResourceManager.GetString("LabelItemCount", resourceCulture);
            }
        }
        
        internal static string TooltipEditTraktList {
            get {
                return ResourceManager.GetString("TooltipEditTraktList", resourceCulture);
            }
        }
        
        internal static string TooltipDeleteTraktList {
            get {
                return ResourceManager.GetString("TooltipDeleteTraktList", resourceCulture);
            }
        }
    }
}
