//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Trash {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Trash() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Trash", typeof(Trash).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonDeleteFromDatabase {
            get {
                return ResourceManager.GetString("ButtonDeleteFromDatabase", resourceCulture);
            }
        }
        
        internal static string ButtonClearSelection {
            get {
                return ResourceManager.GetString("ButtonClearSelection", resourceCulture);
            }
        }
        
        internal static string ButtonSelectAll {
            get {
                return ResourceManager.GetString("ButtonSelectAll", resourceCulture);
            }
        }
        
        internal static string ButtonEmptyTrash {
            get {
                return ResourceManager.GetString("ButtonEmptyTrash", resourceCulture);
            }
        }
        
        internal static string LabelTrash {
            get {
                return ResourceManager.GetString("LabelTrash", resourceCulture);
            }
        }
        
        internal static string LabelMovies {
            get {
                return ResourceManager.GetString("LabelMovies", resourceCulture);
            }
        }
        
        internal static string LabelShows {
            get {
                return ResourceManager.GetString("LabelShows", resourceCulture);
            }
        }
        
        internal static string LabelSeasons {
            get {
                return ResourceManager.GetString("LabelSeasons", resourceCulture);
            }
        }
        
        internal static string LabelEpisodes {
            get {
                return ResourceManager.GetString("LabelEpisodes", resourceCulture);
            }
        }
        
        internal static string LabelArtists {
            get {
                return ResourceManager.GetString("LabelArtists", resourceCulture);
            }
        }
        
        internal static string LabelMusicVideos {
            get {
                return ResourceManager.GetString("LabelMusicVideos", resourceCulture);
            }
        }
        
        internal static string LabelOtherVideos {
            get {
                return ResourceManager.GetString("LabelOtherVideos", resourceCulture);
            }
        }
        
        internal static string LabelSongs {
            get {
                return ResourceManager.GetString("LabelSongs", resourceCulture);
            }
        }
        
        internal static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        internal static string LabelRemoteStreams {
            get {
                return ResourceManager.GetString("LabelRemoteStreams", resourceCulture);
            }
        }
        
        internal static string LabelSeeAll {
            get {
                return ResourceManager.GetString("LabelSeeAll", resourceCulture);
            }
        }
        
        internal static string LabelNothingToSee {
            get {
                return ResourceManager.GetString("LabelNothingToSee", resourceCulture);
            }
        }
        
        internal static string DialogDeleteFromDatabase {
            get {
                return ResourceManager.GetString("DialogDeleteFromDatabase", resourceCulture);
            }
        }
        
        internal static string LabelContainsMediaItems {
            get {
                return ResourceManager.GetString("LabelContainsMediaItems", resourceCulture);
            }
        }
    }
}
