//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErsatzTV.Locals.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Watermarks {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Watermarks() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ErsatzTV.Locals.Pages.Watermarks", typeof(Watermarks).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ButtonAddWatermark {
            get {
                return ResourceManager.GetString("ButtonAddWatermark", resourceCulture);
            }
        }
        
        internal static string LabelWatermarks {
            get {
                return ResourceManager.GetString("LabelWatermarks", resourceCulture);
            }
        }
        
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        internal static string LabelImage {
            get {
                return ResourceManager.GetString("LabelImage", resourceCulture);
            }
        }
        
        internal static string LabelMode {
            get {
                return ResourceManager.GetString("LabelMode", resourceCulture);
            }
        }
        
        internal static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        internal static string TooltipEditWatermark {
            get {
                return ResourceManager.GetString("TooltipEditWatermark", resourceCulture);
            }
        }
        
        internal static string TooltipCopyWatermark {
            get {
                return ResourceManager.GetString("TooltipCopyWatermark", resourceCulture);
            }
        }
        
        internal static string TooltipDeleteWatermark {
            get {
                return ResourceManager.GetString("TooltipDeleteWatermark", resourceCulture);
            }
        }
        
        internal static string LabelChannelLogo {
            get {
                return ResourceManager.GetString("LabelChannelLogo", resourceCulture);
            }
        }
        
        internal static string DialogDeleteWatermark {
            get {
                return ResourceManager.GetString("DialogDeleteWatermark", resourceCulture);
            }
        }
        
        internal static string DialogCopyWatermark {
            get {
                return ResourceManager.GetString("DialogCopyWatermark", resourceCulture);
            }
        }
    }
}
